### ISSUE TITLE
is this source code available? 

### ISSUE THREAD

**Issue by RonaldYuren** [JasonManesis/Ship-Detection-on-Remote-Sensing-Synthetic-Aperture-Radar-Data#1]
Hi,
may I just ask that this github's code is available?

Could I run by meself with pytorch you have mentioned in readme, if OK, are there any step or dataset position can provide to help me to use more quickly?

**Comment by jasonmanesis** [comment]
Hi, all the code you will need is in the "Notebooks" directory of this repo. The Faster-RCNN models utilize the Detectron2 framework and the YOLOv5 model is implemented in Pytorch. You can download the dataset I used from here: https://github.com/chaozhong2010/HRSID

**Comment by RonaldYuren** [comment]
OK   I would try running these days, thanks for repling me !!!   
if i have other question would ask!!!

**Comment by jasonmanesis** [comment]
It's my pleasure. If you have any questions you can mail me.

**Comment by RonaldYuren** [comment]
Hi , can I just use google colab to run that "yolov5" file?   I found that I have some trouble in create a Dataset folder in MyDrive.
![image](https://user-images.githubusercontent.com/95292013/180640309-5a4d9f5d-a80b-4062-9bdf-ac72ea3672e3.png)


the error msg is :   
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-779a60aa5918> in <module>()
      1 # Overwrite the original .yaml file.
      2 path_4_saving = '/content/drive/MyDrive/Datasets/HRSID_YOLO/dataset.yaml'
----> 3 with open(path_4_saving, 'w') as outfile:
      4     yaml.dump(parsed_yaml_file, outfile, default_flow_style=False)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Datasets/HRSID_YOLO/dataset.yaml'

**Comment by jasonmanesis** [comment]
You can run the code locally if you want, or you can upload the HRSID
dataset in a folder on your drive. In order to run the YOLO algorithm you
should change the annotations to the expected "YOLO" format. Before you run
the above code cell you must be sure that the output directory exists.


Στις Κυρ, 24 Ιουλ 2022, 12:12 ο χρήστης RonaldYuren <
***@***.***> έγραψε:

**Comment by RonaldYuren** [comment]
So  i need to create a folder "Dataset"  and put HRSID dataset in it by hand ?

Also, i need to change this path in this picture to  that Dataset's path?
![image](https://user-images.githubusercontent.com/95292013/180653947-742d1385-9504-4c54-8950-fdb4fdf51d86.png)

**Comment by jasonmanesis** [comment]
You must create a folder which contains the dataset in YOLO format and then
you should enter this exact path to the code.

Στις Κυρ, 24 Ιουλ 2022, 18:19 ο χρήστης RonaldYuren <
***@***.***> έγραψε:

**Comment by RonaldYuren** [comment]
what is the "dataset in YOLO format"
so if I want to process "Yolov5_Pytorch.ipynb"   there is another "yolo file"  I need to  download?  is that "hyp.yaml" ??

**Comment by RonaldYuren** [comment]
> what is the "dataset in YOLO format" so if I want to process "Yolov5_Pytorch.ipynb" there is another "yolo file" I need to download? is that "hyp.yaml" ??

Ohhhhhh!!
I have found that yolo_dataset, i will work on this these days

**Comment by RonaldYuren** [comment]
HI,  I didn't see the weight file like this picture.
![image](https://user-images.githubusercontent.com/95292013/182543140-47652a7f-f6dc-4ae6-b320-0dbb1e0a6e7e.png)


![image](https://user-images.githubusercontent.com/95292013/182543232-05f03ef2-b763-4c81-bf3e-731c398a6b8d.png)
Only inside the yolov5 I see some similar folder but I am not sure about it, and how to use the "exp" folder ????
